
package soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "FactorialImplService", targetNamespace = "http://soap/", wsdlLocation = "http://localhost:2121/soap/fact?wsdl")
public class FactorialImplService
    extends Service
{

    private final static URL FACTORIALIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException FACTORIALIMPLSERVICE_EXCEPTION;
    private final static QName FACTORIALIMPLSERVICE_QNAME = new QName("http://soap/", "FactorialImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:2121/soap/fact?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        FACTORIALIMPLSERVICE_WSDL_LOCATION = url;
        FACTORIALIMPLSERVICE_EXCEPTION = e;
    }

    public FactorialImplService() {
        super(__getWsdlLocation(), FACTORIALIMPLSERVICE_QNAME);
    }

    public FactorialImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), FACTORIALIMPLSERVICE_QNAME, features);
    }

    public FactorialImplService(URL wsdlLocation) {
        super(wsdlLocation, FACTORIALIMPLSERVICE_QNAME);
    }

    public FactorialImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, FACTORIALIMPLSERVICE_QNAME, features);
    }

    public FactorialImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FactorialImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns FactorialDao
     */
    @WebEndpoint(name = "FactorialImplPort")
    public FactorialDao getFactorialImplPort() {
        return super.getPort(new QName("http://soap/", "FactorialImplPort"), FactorialDao.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FactorialDao
     */
    @WebEndpoint(name = "FactorialImplPort")
    public FactorialDao getFactorialImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://soap/", "FactorialImplPort"), FactorialDao.class, features);
    }

    private static URL __getWsdlLocation() {
        if (FACTORIALIMPLSERVICE_EXCEPTION!= null) {
            throw FACTORIALIMPLSERVICE_EXCEPTION;
        }
        return FACTORIALIMPLSERVICE_WSDL_LOCATION;
    }

}
