
package employee;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SalaryDao", targetNamespace = "http://employee/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SalaryDao {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "calcularSalarioPorHoras", targetNamespace = "http://employee/", className = "employee.CalcularSalarioPorHoras")
    @ResponseWrapper(localName = "calcularSalarioPorHorasResponse", targetNamespace = "http://employee/", className = "employee.CalcularSalarioPorHorasResponse")
    @Action(input = "http://employee/SalaryDao/calcularSalarioPorHorasRequest", output = "http://employee/SalaryDao/calcularSalarioPorHorasResponse")
    public double calcularSalarioPorHoras(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        double arg1);

}
