
package employee;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SalaryDaoImplService", targetNamespace = "http://employee/", wsdlLocation = "http://localhost:2121/soap/salary?wsdl")
public class SalaryDaoImplService
    extends Service
{

    private final static URL SALARYDAOIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException SALARYDAOIMPLSERVICE_EXCEPTION;
    private final static QName SALARYDAOIMPLSERVICE_QNAME = new QName("http://employee/", "SalaryDaoImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:2121/soap/salary?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SALARYDAOIMPLSERVICE_WSDL_LOCATION = url;
        SALARYDAOIMPLSERVICE_EXCEPTION = e;
    }

    public SalaryDaoImplService() {
        super(__getWsdlLocation(), SALARYDAOIMPLSERVICE_QNAME);
    }

    public SalaryDaoImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SALARYDAOIMPLSERVICE_QNAME, features);
    }

    public SalaryDaoImplService(URL wsdlLocation) {
        super(wsdlLocation, SALARYDAOIMPLSERVICE_QNAME);
    }

    public SalaryDaoImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SALARYDAOIMPLSERVICE_QNAME, features);
    }

    public SalaryDaoImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SalaryDaoImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SalaryDao
     */
    @WebEndpoint(name = "SalaryDaoImplPort")
    public SalaryDao getSalaryDaoImplPort() {
        return super.getPort(new QName("http://employee/", "SalaryDaoImplPort"), SalaryDao.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SalaryDao
     */
    @WebEndpoint(name = "SalaryDaoImplPort")
    public SalaryDao getSalaryDaoImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://employee/", "SalaryDaoImplPort"), SalaryDao.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SALARYDAOIMPLSERVICE_EXCEPTION!= null) {
            throw SALARYDAOIMPLSERVICE_EXCEPTION;
        }
        return SALARYDAOIMPLSERVICE_WSDL_LOCATION;
    }

}
